spring:
  jmx.enabled: false
  resources.static-locations: classpath:/static
  main.banner-mode: "off"
  profiles.active: local
  datasource:
    driver: oracle.jdbc.OracleDriver

---

spring:
  profiles: local
  datasource:
    driver: org.h2.Driver
    initialization-mode: always
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=ORACLE
    password: pass
    username: user
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
